spring:
   datasource:
      url: jdbc:mysql://localhost:3306/ies
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: Tanushri
   jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect
